<a href="https://colab.research.google.com/github/riyarani6180/DataCleaning/blob/main/Cleaning_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
dataset=pd.read_csv("Algerian.csv")

In [ ]:
dataset.head()

,Unnamed: 0,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
0,1,1,6,2012,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,notfire,Bejaia
1,2,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,notfire,Bejaia
2,3,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,notfire,Bejaia
3,4,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,notfire,Bejaia
4,5,5,6,2012,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,notfire,Bejaia

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   243 non-null    int64
 1   day          243 non-null    int64
 2   month        243 non-null    int64
 3   year         243 non-null    int64
 4   Temperature  243 non-null    int64
 5   RH           243 non-null    int64
 6   Ws           243 non-null    int64
 7   Rain         243 non-null    float64
 8   FFMC         243 non-null    float64
 9   DMC          243 non-null    float64
 10  DC           243 non-null    float64
 11  ISI          243 non-null    float64
 12  BUI          243 non-null    float64
 13  FWI          243 non-null    float64
 14  Classes      243 non-null    object
 15  Region       243 non-null    object
dtypes: float64(7), int64(7), object(2)
memory usage: 30.5+ KB

In [ ]:
### data cleaning
### mising values
dataset[dataset.isnull().any(axis=1)]

Empty DataFrame
Columns: [Unnamed: 0, day, month, year, Temperature, RH, Ws, Rain, FFMC, DMC, DC, ISI, BUI, FWI, Classes, Region]
Index: []

In [ ]:
dataset.loc[:122,'Region']=0
dataset.loc[122:,'Region']=1
df=dataset

In [ ]:
df[['Region']]=df[['Region']].astype(int)

In [ ]:
df.head()

,Unnamed: 0,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
0,1,1,6,2012,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,notfire,0
1,2,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,notfire,0
2,3,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,notfire,0
3,4,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,notfire,0
4,5,5,6,2012,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,notfire,0

In [ ]:
df.isnull().sum()

Unnamed: 0     0
day            0
month          0
year           0
Temperature    0
RH             0
Ws             0
Rain           0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        0
Region         0
dtype: int64

In [ ]:
pd.read_csv("sidi-Bel.csv")

,month,year,Temperature,RH,Ws,Rain,FFMC,DC,ISI,BUI,FWI,Classes
0,6,2012,32,71,12,0.7,57.1,8.2,0.6,2.8,0.2,not fire
1,6,2012,30,73,13,4.0,55.7,7.8,0.6,2.9,0.2,not fire
2,6,2012,29,80,14,2.0,48.7,7.6,0.3,2.6,0.1,not fire
3,6,2012,30,64,14,0.0,79.4,15.4,2.2,5.6,1.0,not fire
4,6,2012,32,60,14,0.2,77.1,17.6,1.8,6.5,0.9,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...
117,9,2012,30,65,14,0.0,85.4,44.5,4.5,16.9,6.5,fire
118,9,2012,28,87,15,4.4,41.1,8.0,0.1,6.2,0.0,not fire
119,9,2012,27,87,29,0.5,45.9,7.9,0.4,3.4,0.2,not fire
120,9,2012,24,54,18,0.1,79.7,15.2,1.7,5.1,0.7,not fire
121,9,2012,24,64,15,0.2,67.3,16.5,1.2,4.8,0.5,not fire

In [ ]:
### removing null values
df.dropna().reset_index(drop=True)
df.head()

,Unnamed: 0,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
0,1,1,6,2012,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,notfire,0
1,2,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,notfire,0
2,3,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,notfire,0
3,4,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,notfire,0
4,5,5,6,2012,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,notfire,0

In [ ]:
df.isnull().sum()

Unnamed: 0     0
day            0
month          0
year           0
Temperature    0
RH             0
Ws             0
Rain           0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        0
Region         0
dtype: int64

In [ ]:
### remove the 122 row
df.drop(122).reset_index(drop=True)

,Unnamed: 0,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
0,1,1,6,2012,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,notfire,0
1,2,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,notfire,0
2,3,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,notfire,0
3,4,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,notfire,0
4,5,5,6,2012,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,notfire,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,242,26,9,2012,30,65,14,0.0,85.4,16.0,44.5,4.5,16.9,6.5,fire,1
238,243,27,9,2012,28,87,15,4.4,41.1,6.5,8.0,0.1,6.2,0.0,notfire,1
239,244,28,9,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,notfire,1
240,245,29,9,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,notfire,1
241,246,30,9,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,notfire,1

In [ ]:
df.iloc[[122]]

,Unnamed: 0,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
122,125,1,6,2012,32,71,12,0.7,57.1,2.5,8.2,0.6,2.8,0.2,notfire,1

In [ ]:
df.columns

Index(['Unnamed: 0', 'day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain',
       'FFMC', 'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Region'],
      dtype='object')

In [ ]:
## fix spaces in column name
df.columns=df.columns.str.strip()

In [ ]:
df.columns

Index(['Unnamed: 0', 'day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain',
       'FFMC', 'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Region'],
      dtype='object')

In [ ]:
## change the required columns as integer data type
df[['month','year','Temperature','RH','Ws']]=df[['month','year','Temperature','RH','Ws']].astype(int)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   243 non-null    int64
 1   day          243 non-null    int64
 2   month        243 non-null    int64
 3   year         243 non-null    int64
 4   Temperature  243 non-null    int64
 5   RH           243 non-null    int64
 6   Ws           243 non-null    int64
 7   Rain         243 non-null    float64
 8   FFMC         243 non-null    float64
 9   DMC          243 non-null    float64
 10  DC           243 non-null    float64
 11  ISI          243 non-null    float64
 12  BUI          243 non-null    float64
 13  FWI          243 non-null    float64
 14  Classes      243 non-null    object
 15  Region       243 non-null    int64
dtypes: float64(7), int64(8), object(1)
memory usage: 30.5+ KB

In [ ]:
### changing the opthers columns to float datatype
objects=[features for features in df.columns if df[features].dtype=='O']
##df[['rain','ffmc','DMC','DC','ISI','BUI','FWI']]=df[['rain','ffmc','DMC','DC','ISI','BUI','FWI']].astype(float)

In [ ]:
for i in objects:
  if i!='Classes':
    df[i]=df[i].astype(float)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   243 non-null    int64
 1   day          243 non-null    int64
 2   month        243 non-null    int64
 3   year         243 non-null    int64
 4   Temperature  243 non-null    int64
 5   RH           243 non-null    int64
 6   Ws           243 non-null    int64
 7   Rain         243 non-null    float64
 8   FFMC         243 non-null    float64
 9   DMC          243 non-null    float64
 10  DC           243 non-null    float64
 11  ISI          243 non-null    float64
 12  BUI          243 non-null    float64
 13  FWI          243 non-null    float64
 14  Classes      243 non-null    object
 15  Region       243 non-null    int64
dtypes: float64(7), int64(8), object(1)
memory usage: 30.5+ KB

In [ ]:
objects

['Classes']

In [ ]:
df.describe()

,Unnamed: 0,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Region
count,243.000000,243.000000,243.000000,243.0,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000
mean,123.316872,15.761317,7.502058,2012.0,32.152263,62.041152,15.493827,0.762963,77.842387,14.680658,49.430864,4.742387,16.690535,7.035391,0.497942
std,71.540562,8.842552,1.114793,0.0,3.628039,14.828160,2.811385,2.003207,14.349641,12.393040,47.665606,4.154234,14.228421,7.440568,0.501028
min,1.000000,1.000000,6.000000,2012.0,22.000000,21.000000,6.000000,0.000000,28.600000,0.700000,6.900000,0.000000,1.100000,0.000000,0.000000
25%,61.500000,8.000000,7.000000,2012.0,30.000000,52.500000,14.000000,0.000000,71.850000,5.800000,12.350000,1.400000,6.000000,0.700000,0.000000
50%,122.000000,16.000000,8.000000,2012.0,32.000000,63.000000,15.000000,0.000000,83.300000,11.300000,33.100000,3.500000,12.400000,4.200000,0.000000
75%,185.500000,23.000000,8.000000,2012.0,35.000000,73.500000,17.000000,0.500000,88.300000,20.800000,69.100000,7.250000,22.650000,11.450000,1.000000
max,246.000000,31.000000,9.000000,2012.0,42.000000,90.000000,29.000000,16.800000,96.000000,65.900000,220.400000,19.000000,68.000000,31.100000,1.000000

In [ ]:
### let save the clean dataset
df.to_csv("cleaned_dataset.csv",index=False)

In [ ]:
### exploratory data analysis
## drop day,month,year
df_copy=df.drop(['day','month','year'],axis=1)

In [ ]:
df_copy

,Unnamed: 0,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
0,1,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,notfire,0
1,2,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,notfire,0
2,3,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,notfire,0
3,4,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,notfire,0
4,5,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,notfire,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,242,30,65,14,0.0,85.4,16.0,44.5,4.5,16.9,6.5,fire,1
239,243,28,87,15,4.4,41.1,6.5,8.0,0.1,6.2,0.0,notfire,1
240,244,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,notfire,1
241,245,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,notfire,1
242,246,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,notfire,1

In [ ]:
df_copy['Classes'].value_counts()

Classes
1    243
Name: count, dtype: int64

In [ ]:
## encoding of the cateogry in classes
df_copy['Classes']=np.where(df_copy['Classes']=='not fire'.str.contains('not fire'),0,1)

AttributeError: 'str' object has no attribute 'str'

In [ ]:
df_copy.head()

,Unnamed: 0,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region,classes
0,1,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,1,0,1
1,2,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,1,0,1
2,3,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,1,0,1
3,4,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,1,0,1
4,5,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,1,0,1

In [ ]:
df_copy['Classes'].value_counts()

Classes
1    243
Name: count, dtype: int64